---
services:
  msg_postgres:
    image: "postgres:15"
    container_name: dispatch_postgres
    environment:
      POSTGRES_DB: dispatch_db
      POSTGRES_USER: dispatch
      POSTGRES_PASSWORD: dispatching
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dispatch", "-d", "dispatch_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "55777:5432"
  dispatcherd1:
    container_name: dispatcherd1
    working_dir: /dispatcherd
    build:
      context: .
      dockerfile: tools/demo/Dockerfile
    environment:
      PATH: /dispatcherd/venv/bin:$PATH
      PYTHONPATH: .
    command: dispatcherd --config=/dispatcherd/dispatcher1.yml
    depends_on:
      msg_postgres:
        condition: service_healthy
  dispatcherd2:
    container_name: dispatcherd2
    build:
      context: .
      dockerfile: tools/demo/Dockerfile
    environment:
      PATH: /dispatcherd/venv/bin:$PATH
      PYTHONPATH: .
    command: dispatcherd --config=/dispatcherd/dispatcher2.yml
    depends_on:
      msg_postgres:
        condition: service_healthy
